import type { Metadata } from "next";
import "./globals.css";
import SmoothScrolling from "@/components/SmoothScrolling";
import { cn } from "@/lib/utils";
import { basisGrotesqueArabic } from "@/lib/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen font-sans antialiased", basisGrotesqueArabic.variable)}>
        <SmoothScrolling>{children}</SmoothScrolling>
      </body>
    </html>
  );
}
